# This is a basic workflow to help you get started with Actions

name: Compile Latex


# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.1.0
        with:
            root_file: SRS.tex
            working_directory: ./docs/SRS
            
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Compile LaTeX PDF
